### ISSUE TITLE
Could anybody make an tutorial?

### ISSUE THREAD

**Issue by D0V15** [tobozo/Rotatey_Cube#1]
@tobozo this looks very cool and i would like to make it for myself but I'm a  new one in arduino stuff. So before I buy things that i can't program myself could you make an tutorial? Thanks!

**Comment by tobozo** [comment]
Hey @D0V15,

I'm not sure what kind of tutorial you're talking about.
The ReadME has the essentials (pinout, hardware list) and the code can be used as is.

Please explain what is missing or what you expect and I'll do my best to add it.

**Comment by D0V15** [comment]
Yeah the pinout and the hardware are there but I'm missing the programing part because this line:
"The code is a remix of the original, it's using u8glib and mpu6050 libraries instead of Adafruit and ITG-3200." Doesn't say anything to me (as I said I'm new to the arduino)

**Comment by D0V15** [comment]
Could you at least show me where the code is? So I could copy-paste it into the arduino ide

**Comment by tobozo** [comment]
Dunno if you cloned this repo or just downloaded the zip, but make sure the folder is named "Rotatey_Cube", then browse it and open "Rotatey_Cube.ino" in your Arduino IDE. The other files are just dependancies and don't need to be edited, but they are required so don't delete them :-)

If you get a compilation error after hitting the "compile" button, it's probably the Arduino IDE complaining about a missing library (u8glib), which you can download from the [Arduino IDE Library Manager](https://www.arduino.cc/en/Guide/Libraries).

Make sure you install "u8glib". If you get errors after that, try googling them, or open a new issue here.

**Comment by D0V15** [comment]
Thanks for the help.I will try to make it when  the components arrive form china :D

**Comment by tobozo** [comment]
You can test compilation without the components :p

**Comment by D0V15** [comment]
The code is to big for my Nano

**Comment by zarikadzer** [comment]
It works with Nano 328: https://drive.google.com/open?id=0B0hTFQYJ3l_fMTdNT1FnUjhWVTA
If you want smaller code, just try my fork. I've started optimizations and upgrades for my pet-project.

**Comment by D0V15** [comment]
God damn it now I will have to buy a new nano
@tobozo could you try to make the code a little shorter? 
Now it uses 123% of the 168 nano 
Thanks!

**Comment by tobozo** [comment]
The best I can get to is 122% by updating some i2c-dev files.

I just published the other version working on ESP8266 if you can't wait for your Nano 328 to get delivered.

**Comment by D0V15** [comment]
can I use an Arduino uno instead of nano?
