### ISSUE TITLE
I don't see the esp pinout 

### ISSUE THREAD

**Issue by D0V15** [tobozo/Rotatey_Cube#2]
I don't understand where to connect the esp

**Comment by tobozo** [comment]
A5 and A4 become D4 and D3, A0 stays A0. Just find those pins on your board and connect them accordingly to the Arduino Schema.

If you prefer using other pins (i.e. on Wemos the SDA/SCL are on D2/D1), just change those values:

- SSD1306 display(0x3c, **D3**, **D4**);

Be aware the ESP version of this code does not produce exactly the same behaviour as seen on Arduino. You will have to play with it :hammer: :wrench:

**Comment by D0V15** [comment]
So if I understood:
OLED to MPU
    VCC => 5V
    GND => GND
    SCL => A5
    SDA => A4
 MPU to NodeMCU
    AD0 => GND
    INT => D2
If I'm wrong please correct me

**Comment by D0V15** [comment]
I used ESP8266 board expansion and it doesn't show up any port that I can use(only serial)

**Comment by tobozo** [comment]
Then the problem is on you not finding your pins, not the code.

I'm sorry I can't assist you on that.
